spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onulbuinessdb
    username: onulbuiness
    password: Onulbuiness2024!

  security:
    headers:
      content-security-policy: "script-src 'self' http://ajax.googleapis.com"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
#    root: info
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG

jwt:
  key: wERjtIdxQ8lNjF0w/AAiN6HqTASaCAUzSq6nbKefMwf5CbPE8GvwLsClz94uVt9Q1esxYwwXVU+BYn7/mR01Qg==
  time: 2592000000
