server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  security:
    headers:
      content-security-policy: "script-src 'self' http://ajax.googleapis.com"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+9
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-time: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-time: ${JWT_REFRESH_TOKEN_TIME}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
